### ISSUE TITLE
R libraries on ACAD1:

### ISSUE THREAD

**Issue by EisenRa** [ACAD-UofA/Bioinformatics-Wiki#10]
Having errors running mapDamage model on ACAD1 through paleomix:

<mapDamage (model): 'A15389_China_MigEnrich_1.fastq.gz.PgingivalisMLST.mapDamage/A15389_China_MigEnrich_1'>
  Error ('NodeError') occurred running command:
    Error(s) running Node:
    	Temporary directory: '/tmp/a1683110/bam_pipeline/06e0e955-216b-4985-8aff-c15d8e2956ad'

    <Command = ['mapDamage', '--stats-only', '-r',
    	           'MigrationEnrichment/01_References/Pgingivalis-MLST/Pgingivalis_MLST.fasta',
    	           '-d', '/tmp/a1683110/bam_pipeline/06e0e955-216b-4985-8aff-c15d8e2956ad']
    	 Status  = Exited with return-code 1
    	 STDOUT* = '/tmp/a1683110/bam_pipeline/06e0e955-216b-4985-8aff-c15d8e2956ad/pipe_mapDamage.stdout'
    	 STDERR* = '/tmp/a1683110/bam_pipeline/06e0e955-216b-4985-8aff-c15d8e2956ad/pipe_mapDamage.stderr'
    	 CWD     = '/localscratch/EisenRa/0__PALEOMIX'>

__________
STDERR: 

[a1683110@acad1 0__PALEOMIX]$ more /tmp/a1683110/bam_pipeline/06e0e955-216b-4985-8aff-c15d8e2956ad/pipe_mapDamage.stderr
Started with the command: /data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-2.7.13/bin/mapDamage --stats-only -r MigrationE
nrichment/01_References/Pgingivalis-MLST/Pgingivalis_MLST.fasta -d /tmp/a1683110/bam_pipeline/06e0e955-216b-4985-8aff-c15d8e2956ad
Performing Bayesian estimates
Error in compileCode(f, code, language = language, verbose = verbose) :
  Compilation ERROR, function(s)/method(s) not created! In file included from /apps/software/GCCcore/5.4.0/include/c++/5.4.0/tr1/has
htable.h:36:0,
                 from /apps/software/GCCcore/5.4.0/include/c++/5.4.0/tr1/unordered_map:41,
                 from /apps/software/R/3.3.1-foss-2016b/lib64/R/library/Rcpp/include/Rcpp/platform/compiler.h:172,
                 from /apps/software/R/3.3.1-foss-2016b/lib64/R/library/Rcpp/include/Rcpp/r/headers.h:48,
                 from /apps/software/R/3.3.1-foss-2016b/lib64/R/library/Rcpp/include/RcppCommon.h:29,
                 from /data/acad/apps/software/R-packages/R-3.3.1-foss-2016b/lib/RcppGSL/include/RcppGSLForward.h:25,
                 from /data/acad/apps/software/R-packages/R-3.3.1-foss-2016b/lib/RcppGSL/include/RcppGSL.h:25,
                 from file13b619019d85.cpp:3:
/apps/software/GCCcore/5.4.0/include/c++/5.4.0/tr1/hashtable_policy.h:383:5: internal compiler error: Illegal instruction
     _Prime_rehash_policy(float __
Calls: source ... withVisible -> eval -> eval -> cxxfunction -> compileCode
In addition: Warning message:
running command '/apps/software/R/3.3.1-foss-2016b/lib64/R/bin/R CMD SHLIB file13b619019d85.cpp 2> file13b619019d85.cpp.err.txt' had
 status 1
The Bayesian statistics program failed to finish
Traceback (most recent call last):
  File "/data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-2.7.13/bin/mapDamage", line 382, in <module>
    sys.exit(main())
  File "/data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-2.7.13/bin/mapDamage", line 202, in main
    mapdamage.rscript.run_stats(options)
  File "/data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-2.7.13/lib/python2.7/site-packages/mapdamage/rscript.py", line 14
4, in run_stats
    raise e
subprocess.CalledProcessError: Command '['Rscript', '/data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-2.7.13/lib/python2.7
/site-packages/mapdamage/Rscripts/stats/runGeneral.R', '--args', '30', '10000', '10', '50000', '0', '0', '1', '1', '0', '0', '1', '1
2', '/tmp/a1683110/bam_pipeline/06e0e955-216b-4985-8aff-c15d8e2956ad/', '/data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-
2.7.13/lib/python2.7/site-packages/mapdamage/Rscripts/stats/', '/tmp/a1683110/bam_pipeline/06e0e955-216b-4985-8aff-c15d8e2956ad/Stat
s_out', '0', '0', '0', '/tmp/a1683110/bam_pipeline/06e0e955-216b-4985-8aff-c15d8e2956ad/acgt_ratio.csv', '0', '0']' returned non-zer
o exit status 1

**Comment by EisenRa** [comment]
Also having an issue on ACAD2:

[a1683110@acad2 ~]$ more /tmp/a1683110/bam_pipeline/bam_pipeline.20170904_161224_00.log
------------------------------------------------------------
2017-09-04 16:13:07,064 -- ERROR:
<mapDamage (model): 'A15462_Vanuatu_MigEnrich_1.fastq.gz.OmpA.mapDamage/A15462_Vanuatu_MigEnrich_1'>
  Error ('NodeError') occurred running command:
    Error(s) running Node:
    	Temporary directory: '/tmp/a1683110/bam_pipeline/9a18afc4-24cf-48a1-8c8f-f56b2726f24b'

    <Command = ['mapDamage', '--stats-only', '-r', '01_References/Core-genes/OmpA.fasta', '-d',
    	           '/tmp/a1683110/bam_pipeline/9a18afc4-24cf-48a1-8c8f-f56b2726f24b']
    	 Status  = Exited with return-code 1
    	 STDOUT* = '/tmp/a1683110/bam_pipeline/9a18afc4-24cf-48a1-8c8f-f56b2726f24b/pipe_mapDamage.stdout'
    	 STDERR* = '/tmp/a1683110/bam_pipeline/9a18afc4-24cf-48a1-8c8f-f56b2726f24b/pipe_mapDamage.stderr'
    	 CWD     = '/localscratch/EisenRa/0__PALEOMIX/MigrationEnrichment'>

------------------------------------------------------------
2017-09-04 16:13:07,077 -- ERROR:
<mapDamage (model): 'A15732_Fiji-UnEnriched_1.fastq.gz.DnaG.mapDamage/A15732_Fiji-UnEnriched_1'>
  Error ('NodeError') occurred running command:
    Error(s) running Node:
    	Temporary directory: '/tmp/a1683110/bam_pipeline/d7d8a962-e06f-4faa-b019-ff25d092d52d'

    <Command = ['mapDamage', '--stats-only', '-r', '01_References/Core-genes/DnaG.fasta', '-d',
    	           '/tmp/a1683110/bam_pipeline/d7d8a962-e06f-4faa-b019-ff25d092d52d']
    	 STDOUT* = '/tmp/a1683110/bam_pipeline/d7d8a962-e06f-4faa-b019-ff25d092d52d/pipe_mapDamage.stdout'
    	 STDERR* = '/tmp/a1683110/bam_pipeline/d7d8a962-e06f-4faa-b019-ff25d092d52d/pipe_mapDamage.stderr'
    	 CWD     = '/localscratch/EisenRa/0__PALEOMIX/MigrationEnrichment'>

    Error running commands:
      Call = ['mapDamage', '--stats-only', '-r', '%(IN_REFERENCE)s', '-d', '%(TEMP_DIR)s']
      **Error = OSError(11, 'Resource temporarily unavailable')**

------------------------------------------------------------
2017-09-04 16:13:07,089 -- ERROR:
<mapDamage (model): 'A15753_Marquesas-UnEnriched_2.fastq.gz.DnaN.mapDamage/A15753_Marquesas-UnEnriched_2'>
  Error ('NodeError') occurred running command:
    Error(s) running Node:
    	Temporary directory: '/tmp/a1683110/bam_pipeline/d12eb0b1-e374-4804-b0a7-ca71e782a177'

    <Command = ['mapDamage', '--stats-only', '-r', '01_References/Core-genes/DnaN.fasta', '-d',
    	           '/tmp/a1683110/bam_pipeline/d12eb0b1-e374-4804-b0a7-ca71e782a177']
    	 STDOUT* = '/tmp/a1683110/bam_pipeline/d12eb0b1-e374-4804-b0a7-ca71e782a177/pipe_mapDamage.stdout'
    	 STDERR* = '/tmp/a1683110/bam_pipeline/d12eb0b1-e374-4804-b0a7-ca71e782a177/pipe_mapDamage.stderr'
    	 CWD     = '/localscratch/EisenRa/0__PALEOMIX/MigrationEnrichment'>

    Error running commands:
      Call = ['mapDamage', '--stats-only', '-r', '%(IN_REFERENCE)s', '-d', '%(TEMP_DIR)s']
      **Error = OSError(11, 'Resource temporarily unavailable')**

------------------------------------------------------------
2017-09-04 16:13:07,116 -- ERROR:
<mapDamage (model): 'A15818_Palau-UnEnriched_2.fastq.gz.PgingivalisMLST.mapDamage/A15818_Palau-UnEnriched_2'>
  Error ('NodeError') occurred running command:
    Error(s) running Node:
    	Temporary directory: '/tmp/a1683110/bam_pipeline/8bac80d6-0d11-4344-833f-61739782bdd7'

    <Command = ['mapDamage', '--stats-only', '-r',
    	           '01_References/Pgingivalis-MLST/Pgingivalis_MLST.fasta', '-d',
    	           '/tmp/a1683110/bam_pipeline/8bac80d6-0d11-4344-833f-61739782bdd7']
    	 STDOUT* = '/tmp/a1683110/bam_pipeline/8bac80d6-0d11-4344-833f-61739782bdd7/pipe_mapDamage.stdout'
    	 STDERR* = '/tmp/a1683110/bam_pipeline/8bac80d6-0d11-4344-833f-61739782bdd7/pipe_mapDamage.stderr'
    	 CWD     = '/localscratch/EisenRa/0__PALEOMIX/MigrationEnrichment'>

    Error running commands:
      Call = ['mapDamage', '--stats-only', '-r', '%(IN_REFERENCE)s', '-d', '%(TEMP_DIR)s']
      **Error = OSError(11, 'Resource temporarily unavailable')**

_____

Looking into the stderr file for one of the jobs:

[a1683110@acad2 ~]$ more /tmp/a1683110/bam_pipeline/9a18afc4-24cf-48a1-8c8f-f56b2726f24b/pipe_mapDamage.stderr
Traceback (most recent call last):
  File "/data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-2.7.13/bin/mapDamage", line 382, in <module>
    sys.exit(main())
  File "/data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-2.7.13/bin/mapDamage", line 162, in main
    options = mapdamage.parseoptions.options()
  File "/data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-2.7.13/lib/python2.7/site-packages/mapdamage/parseoptions.
py", line 251, in options
    if check_R_lib():
  File "/data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-2.7.13/lib/python2.7/site-packages/mapdamage/rscript.py",
line 87, in check_R_lib
    if check_R_one_lib(lib):
  File "/data/acad/apps/software/mapDamage/2.0.6-foss-2016b-Python-2.7.13/lib/python2.7/site-packages/mapdamage/rscript.py",
line 75, in check_R_one_lib
    stderr = devnull)
  File "/apps/software/Python/2.7.13-foss-2016b/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/apps/software/Python/2.7.13-foss-2016b/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/apps/software/Python/2.7.13-foss-2016b/lib/python2.7/subprocess.py", line 916, in _execute_child
    self.pid = os.fork()
**OSError: [Errno 11] Resource temporarily unavailable**

**Comment by EisenRa** [comment]
For the ACAD1 issue: looks like the module is missing an R library??

**Missing the following R library Rcpp
The Bayesian estimation has been disabled**

**Comment by grahamgower** [comment]
The ACAD1 issue indeed looks like you may be able to just install the library.

On ACAD2, the `OSError: [Errno 11] Resource temporarily unavailable` from `fork()` might indicate you've reached a limit on the number of simultaneous processes allowed. You can bump this up using ulimit. E.g.

```
[a1158147@acad2 ~]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2065424
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 8192
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[a1158147@acad2 ~]$ ulimit -u
1024
[a1158147@acad2 ~]$ ulimit -u `ulimit -Hu`
[a1158147@acad2 ~]$ ulimit -u
2065424
```

Unfortunately, you'll need to rerun this for any new session you open. (Or put it in your ~/.bash_profile).

**Comment by EisenRa** [comment]
That fixed it -- thanks!
