### ISSUE TITLE
Access to port 8080 for MeganServer users

### ISSUE THREAD

**Issue by laam21** [ACAD-UofA/Bioinformatics-Wiki#3]
In order to work with the samples from MeganServer we need the port 8080 to be open. This was working well with eRSA, but changed when moved to UoA. We have been using a temporary fix, but this fix only works with people that have an ACAD1 cluster account, and some people have been left out  (Andrew, for example).

**Comment by grahamgower** [comment]
I've followed up with ITS, but they may be reluctant to open the port. It may be easier to give Andrew (and others) ssh access via the acad_guest account. Then you can supply him with the appropriate ssh port forwarding command.

**Comment by laam21** [comment]
Solved! Thanks!
