### ISSUE TITLE
Software tools that need to be installed

### ISSUE THREAD

**Issue by laam21** [ACAD-UofA/Bioinformatics-Wiki#4]
List of software that was on ACAD1@ersa but I noticed is missing in ACAD1@UoA:
-pigz
-bioperl
-SOAP and SOAPdenovo
-Velvet and Velvet Optimiser

**Comment by grahamgower** [comment]
I've installed pigz (`module load pigz`) and bioperl (`module load Perl-packages`, see https://github.com/ACAD-UofA/Bioinformatics-Wiki/wiki/Modules#installing-perl-packages ).

**Comment by grahamgower** [comment]
The rest are installed now too.
SOAP: `module load SOAPaligner`
SOAPdenovo: `module load SOAPdenovo2`
Velvet: `module load Velvet`
VelvetOptimiser: `module load VelvetOptimiser`
