### ISSUE TITLE
Unable to access remote MEGAN Server?

### ISSUE THREAD

**Issue by emskell** [ACAD-UofA/Bioinformatics-Wiki#6]
Recently access to the remote MEGAN Server changed so we wouldn't have to tunnel 8080 through SSH. Unsure if related, but I am now experiencing this error when trying to access it:

<img width="722" alt="screen shot 2017-07-06 at 1 49 05 pm" src="https://user-images.githubusercontent.com/29449722/27896586-4c7918b8-625a-11e7-8a5e-076f708e4cd1.png">

I have tried both using Server 'localhost:8080/ACAD_DC' and 'acad1.rc.adelaide.edu.au:8080/ACAD_DC' and receive the same error.

Please let me know if any additional details are required...

**Comment by grahamgower** [comment]
It looks like no one is running a MEGAN server right now. You can check if its running by logging into ACAD1 and running `telnet localhost 8080`, which will give a 'connection refused' error if its not running. E.g.
```
[a1158147@acad1 ~]$ telnet localhost 8080
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
```

**Comment by grahamgower** [comment]
@EisenRa is looking into why its not running.

**Comment by EisenRa** [comment]
Seems to be fixed -- let me know.

**Comment by muslih14** [comment]
Just checked and I too can confirm that it now works.
