### ISSUE TITLE
BBmerge on ACAD1

### ISSUE THREAD

**Issue by laam21** [ACAD-UofA/Bioinformatics-Wiki#8]
Hi!
Today I noticed that bbmerge (BBMap tools) is not available in ACAD1. 
Homepage: https://sourceforge.net/projects/bbmap/

Could you have a look into this?
Thanks

**Comment by grahamgower** [comment]
There's no compilation required for this, so I made a module which loads the dependency (java) and puts the tools in your PATH.
<pre>
$ <b>module spider BBMap</b>
Lmod has detected the following error:  Unable to find: "BBMap"

$ <b>rm -r ~/.lmod.d/</b>
$ <b>module spider BBMap</b>
Rebuilding cache, please wait ... (written to file) done.

----------------------------------------------------------------------------
  BBMap: BBMap/37.36
----------------------------------------------------------------------------

    This module can be loaded directly: module load BBMap/37.36

    Help:
      BBMap short read aligner, and other bioinformatic tools.


$ <b>module load BBMap</b>
$
</pre>
