### ISSUE TITLE
PALEOMIX on ACAD1

### ISSUE THREAD

**Issue by EisenRa** [ACAD-UofA/Bioinformatics-Wiki#9]
Getting a bus error (damn that public transport)

[a1683110@acad1 corals]$ export MODULEPATH=/data/acad/apps/modules/all:$MODULEPATH
[a1683110@acad1 corals]$ module load paleomix-meta
[a1683110@acad1 corals]$ bam_pipeline run --jar-root $JAR_ROOT makefile.yaml
Bus error (core dumped)

**Comment by EisenRa** [comment]
Not getting this error anymore, instead:

Traceback (most recent call last):
  File "/apps/software/Python/2.7.13-foss-2016b/lib/python2.7/logging/__init__.py", line 885, in emit
    self.flush()
  File "/apps/software/Python/2.7.13-foss-2016b/lib/python2.7/logging/__init__.py", line 845, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
Logged from file pipeline.py, line 78

**Comment by grahamgower** [comment]
I guess /tmp is the disk its complaining about? You might try changing the path for paleomix's temp files. E.g.
```
$ mkdir -p /localscratch/EisenRa/tmp
$ bam_pipeline run --jar-root $JAR_ROOT --temp-root=/localscratch/EisenRa/tmp makefile.yaml
```

Not sure why you're getting the Bus error though.

**Comment by EisenRa** [comment]
That did the job, thanks!
